export const tagTypes: Record<string, string> = {
  auth: "auth",
  user: "users",
  employees: "employees",
  divisions: "divisions",
  districts: "districts",
  upzelas: "upzelas",
  orders: "orders",
  addresses: "addresses",
  wishlists: "wishlists",
  products: "products",
  carts: "carts",
  product_categories: "product-categories",
  video_gallery_categories: "video_gallery_categories",
  video_gallaries: "video-gallaries",
  blog_category: "blog-category",
  blog: "blog",
  blog_details: "blog-details",
  testimonials: "testimonials",
  question_answers: "question-answers",
  menu: "menu",
  roles: "roles",
  hero: "hero",
  sustainability: "sustainability",
  sustainability_intro: "sustainability-intro",
  sustainability_pillars: "sustainability-pillars",
  sustainability_roadmap: "sustainability-roadmap",
  destinations: "destinations",
  experiences: "experiences",
  events: "events",
  portfolio: "portfolio",
  innovation_concepts: "innovation-concepts",
  life_aboard_photos: "life-aboard-photos",
  yachts: "yachts",
  about: "about",
  about_explore: "about-explore",
  about_stats: "about-stats",
  about_story: "about-story",
  services: "services",
  gallery: "gallery",
  client_video_reviews: "client-video-reviews",
  bookings: "bookings",
  payments: "payments",
  chat: "chat",
  performance: "performance",
  capture_cards: "capture-cards",
  flight_modes: "flight-modes",
  gimbal_banner: "gimbal-banner",
  durability: "durability",
  video_showcase: "video-showcase",
  accessories_banner: "accessories-banner",
  preorder_banner: "preorder-banner",
  product_bundles: "product-bundles",
  shop_accessories: "shop-accessories",
};

export const tagTypesList: string[] = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.employees,
  tagTypes.divisions,
  tagTypes.districts,
  tagTypes.upzelas,
  tagTypes.orders,
  tagTypes.addresses,
  tagTypes.wishlists,
  tagTypes.products,
  tagTypes.carts,
  tagTypes.product_categories,
  tagTypes.video_gallery_categories,
  tagTypes.video_gallaries,
  tagTypes.blog_category,
  tagTypes.blog,
  tagTypes.blog_details,
  tagTypes.testimonials,
  tagTypes.question_answers,
  tagTypes.menu,
  tagTypes.roles,
  tagTypes.hero,
  tagTypes.sustainability,
  tagTypes.sustainability_intro,
  tagTypes.sustainability_pillars,
  tagTypes.sustainability_roadmap,
  tagTypes.destinations,
  tagTypes.experiences,
  tagTypes.events,
  tagTypes.portfolio,
  tagTypes.innovation_concepts,
  tagTypes.life_aboard_photos,
  tagTypes.yachts,
  tagTypes.about,
  tagTypes.about_explore,
  tagTypes.about_stats,
  tagTypes.about_story,
  tagTypes.services,
  tagTypes.gallery,
  tagTypes.client_video_reviews,
  tagTypes.bookings,
  tagTypes.payments,
  tagTypes.chat,
  tagTypes.performance,
  tagTypes.capture_cards,
  tagTypes.flight_modes,
  tagTypes.gimbal_banner,
  tagTypes.durability,
  tagTypes.video_showcase,
  tagTypes.accessories_banner,
  tagTypes.preorder_banner,
  tagTypes.product_bundles,
  tagTypes.shop_accessories,
];
